#!/usr/bin/env python3
"""
Setup script for OpenRouter integration

Guides the user through configuring the debate system with OpenRouter.
"""

import os
import sys


def print_header():
    print("=" * 60)
    print("Blind Debate Adjudicator - OpenRouter Setup")
    print("=" * 60)
    print()


def check_env_file():
    """Check if .env file exists"""
    env_path = os.path.join(os.path.dirname(__file__), '.env')
    return os.path.exists(env_path)


def create_env_file(api_key, provider, num_judges):
    """Create .env file with configuration"""
    env_path = os.path.join(os.path.dirname(__file__), '.env')
    
    content = f"""# Blind Debate Adjudicator - Environment Configuration
# Generated by setup_openrouter.py

LLM_PROVIDER={provider}
NUM_JUDGES={num_judges}
OPENROUTER_API_KEY={api_key}

# Optional site info for OpenRouter rankings
# SITE_URL=https://your-site.com
# SITE_NAME=Debate System

FACT_CHECK_MODE=OFFLINE
"""
    
    with open(env_path, 'w') as f:
        f.write(content)
    
    return env_path


def main():
    print_header()
    
    # Check for existing .env
    if check_env_file():
        print("⚠️  .env file already exists.")
        response = input("   Overwrite? (y/N): ").strip().lower()
        if response != 'y':
            print("   Setup cancelled.")
            return
    
    print("Step 1: Get your OpenRouter API key")
    print("-" * 60)
    print("1. Go to: https://openrouter.ai/keys")
    print("2. Create an account (or sign in)")
    print("3. Generate an API key")
    print()
    
    api_key = input("Enter your OpenRouter API key: ").strip()
    
    if not api_key.startswith("sk-or-"):
        print("\n⚠️  Warning: OpenRouter keys usually start with 'sk-or-v1-'")
        confirm = input("Continue anyway? (y/N): ").strip().lower()
        if confirm != 'y':
            return
    
    print()
    print("Step 2: Choose provider mode")
    print("-" * 60)
    print("1. openrouter - Single model (cheaper, consistent)")
    print("2. openrouter-multi - Multiple models (expensive, diverse)")
    print()
    
    mode = input("Select (1/2) [1]: ").strip() or "1"
    provider = "openrouter" if mode == "1" else "openrouter-multi"
    
    print()
    print("Step 3: Number of judges")
    print("-" * 60)
    print("Each judge = 1 LLM API call per evaluation")
    print("More judges = more robust scoring but higher cost")
    print()
    print("Recommended: 3-5 judges")
    print()
    
    num_judges = input("Number of judges [5]: ").strip() or "5"
    
    print()
    print("Step 4: Cost Estimate")
    print("-" * 60)
    
    # Rough estimates
    judges = int(num_judges)
    
    if provider == "openrouter":
        # Single model - approximate costs
        models = [
            ("Claude 3.5 Sonnet", 0.003, 0.015),  # $3/$15 per 1M tokens
            ("GPT-4o", 0.005, 0.015),
            ("Llama 3.1 70B", 0.0009, 0.0009),
        ]
        print(f"Using single model with {judges} temperature variations")
    else:
        models = [
            ("Claude 3.5 Sonnet", 0.003, 0.015),
            ("GPT-4o Mini", 0.00015, 0.0006),
            ("Gemini Flash", 0.0001, 0.0004),
            ("Llama 3.1 70B", 0.0009, 0.0009),
            ("Mistral Large", 0.002, 0.006),
        ]
        print(f"Using {judges} different models (true judge diversity)")
    
    print()
    print("Approximate costs per debate snapshot:")
    print("(Assuming ~2K prompt tokens, ~500 completion tokens per judge)")
    print()
    
    total_cost = 0
    for model, input_price, output_price in models[:judges]:
        prompt_cost = (2000 / 1_000_000) * input_price
        completion_cost = (500 / 1_000_000) * output_price
        judge_cost = prompt_cost + completion_cost
        total_cost += judge_cost
        print(f"  {model}: ${judge_cost:.4f}")
    
    print(f"\n  Estimated total per snapshot: ${total_cost:.4f}")
    print()
    
    confirm = input("Create configuration? (Y/n): ").strip().lower() or "y"
    if confirm != 'y':
        print("Setup cancelled.")
        return
    
    # Create .env file
    env_path = create_env_file(api_key, provider, num_judges)
    
    print()
    print("✅ Configuration saved!")
    print(f"   File: {env_path}")
    print()
    print("Next steps:")
    print("  1. Install python-dotenv: pip install python-dotenv")
    print("  2. Start the server: python start_server.py")
    print()
    print("To verify OpenRouter is working:")
    print("  curl http://localhost:5000/api/health")
    print("  curl http://localhost:5000/api/debate/modulation-info")
    print()


if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        print("\n\nSetup cancelled.")
        sys.exit(1)
